sudo: required
services: 
  - docker

before_install:
  - docker build -t jpalmer1026/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jpalmer1026/react-test npm test -- --coverage

after_success:
  - docker build -t jpalmer1026/multi-client ./client
  - docker build -t jpalmer1026/multi-nginx ./nginx
  - docker build -t jpalmer1026/multi-server ./server
  - docker build -t jpalmer1026/multi-worker ./worker
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push jpalmer1026/multi-client
  - docker push jpalmer1026/multi-nginx
  - docker push jpalmer1026/multi-server
  - docker push jpalmer1026/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-705770619677
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY